version: "3.8"

# volumes:
#   wordpress:
#     name: wordpress
#     #driver:
#     #driver_opts:

#   mariadb:

# networks:

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"

  # wordpress:

  # mariadb:

  # # ///////////////// #
  # # ////// BONUS //// #
  # # ///////////////// #

  # adminer:
