services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - /home/mstrauss/data:/var/www/html
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - /home/mstrauss/data:/var/www/html
    secrets:
      - wp_password
      - wp_user
      - wp_root_password
      - wp_root_user
    environment:
      WP_USER: /run/secrets/wp_user
      WP_PASSWORD: /run/secrets/wp_password
      WP_ROOT_USER: /run/secrets/wp_root_user
      WP_ROOT_PASSWORD: /run/secrets/wp_root_password
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    secrets:
      - wp_password
      - wp_user
    environment:
      WP_USER: /run/secrets/wp_user
      WP_PASSWORD: /run/secrets/wp_password
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  inception:
    name: inception

secrets:
  # db_user:
  #   file: ../secrets/db_user.txt
  # db_password:
  #   file: ../secrets/db_password.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_root_user:
    file: ../secrets/wp_root_user.txt
  wp_root_password:
    file: ../secrets/wp_root_password.txt
# volumes:
#   wordpress:
#     name: wordpress
#     #driver:
#     #driver_opts:

# # ///////////////// #
# # ////// BONUS //// #
# # ///////////////// #

# adminer:
