version: "3.8"

# volumes:
#   wordpress:
#     name: wordpress
#     #driver:
#     #driver_opts:

# networks:

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/mstrauss/data:/var/www/html

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - /home/mstrauss/data:/var/www/html

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    environment:
      WP_USER: /run/secrets/wp_user
      WP_PASSWORD: /run/secrets/wp_password
    secrets:
      - wp_password.txt
      - wp_user.txt

secrets:
  wp_user:
    file: ../secrets/wp_user.txt
  wp_password:
    file: ../secrets/wp_password.txt

  # # ///////////////// #
  # # ////// BONUS //// #
  # # ///////////////// #

  # adminer:
